version: '3.7'
services:
  db:
    image: postgres:latest
    platform: linux/arm64/v8
    restart: always
    container_name: 'postres'
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: 'databases'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      TZ: 'Asia/Jakarta'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d databases"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - karyonism-net

volumes:
  postgres-data:
    driver: local

networks:
  karyonism-net:
    driver: bridge